### ISSUE TITLE
Error 500 - windows

### ISSUE THREAD

**Issue by eMeRiKa13** [productdevbook/nuxt3-app#23] opened 2021-11-06 15:23 UTC
### Environment

Nuxt CLI v3.0.0-27255771.f78ec93                                                                                                                                                                                      
RootDir: D:\...\nuxt3-test                                                                                                                                                                     
Nuxt project info:                                                                                                                                                                                                     

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27255771.f78ec93`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.0`

### Describe the bug

After installing the dependencies, yarn dev displays this message:

```
[SSR] Error transforming virtual: D:/.../nuxt3-test/.nuxt/plugins/server.mjs: Error: Failed to resolve import "D:

nuxt3-test/node_modules/@pinia/nuxt/dist/templates/plugin.mjs" from "virtual:D:\...\nuxt3-test\.nuxt\plugins\server.mjs". Does the file exist?
```

and the page returns an error 500:

```
Cannot read properties of undefined (reading 'map')
at Module.normalizePlugins (file:///D:/.../nuxt3-test/.nuxt/dist/server/server.mjs:181:28)
at $id_b7b2f3dc (file:///D:/.../nuxt3-test/.nuxt/dist/server/server.mjs:28:39)
at async __instantiateModule__ (file:///D:/.../nuxt3-test/.nuxt/dist/server/server.mjs:1021:3)
```

**Comment by productdevbook** [comment] 2021-11-06 17:09
yarn update and allselect repo update test please

**Comment by eMeRiKa13** [comment] 2021-11-07 14:45
@productdevbook still error 500. This Pinia issue covers the problem I think https://github.com/posva/pinia/issues/778

**Comment by productdevbook** [comment] 2021-11-08 11:13
> @productdevbook still error 500. This Pinia issue covers the problem I think [posva/pinia#778](https://github.com/posva/pinia/issues/778)

repeat yarn allupdate tested. I think they fixed that problem with the new update.

**Comment by eMeRiKa13** [comment] 2021-11-08 12:07
Unfortunately I have still the same error. 

Could you commit your new package.json to let me check if we have the same versions?

**Comment by productdevbook** [comment] 2021-11-08 14:37
![CleanShot 2021-11-08 at 17 37 03](https://user-images.githubusercontent.com/38668796/140761268-c7788188-b20a-4a15-bb2d-d3ebe67b69e3.png)

**Comment by eMeRiKa13** [comment] 2021-11-08 14:42
I have the same version. And so your nuxt3-app is working for you? No 500 error?

**Comment by productdevbook** [comment] 2021-11-08 15:07
yes yarn dev working, only page http://localhost:3000/modal problem. 

now update my repo check.

**Comment by productdevbook** [comment] 2021-11-08 16:36
fixed all please test

**Comment by darbyjack** [comment] 2021-11-08 17:39
After pulling the latest commit. I am still obtaining an error similar to this. 

```

 WARN  [SSR] Error transforming virtual:C:/Users/glare/Documents/nuxt3-app/.nuxt/plugins/server.mjs: Error: Failed to resolve import "C:UsersglareDocuments
uxt3-app
ode_modules@pinia
uxtdistplugin.mjs" from "virtual:C:\Users\glare\Documents\nuxt3-app\.nuxt\plugins\server.mjs". Does the file exist?
```

```
(node:6812) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
exports is not defined in ES module scope
  at $id_60f0615f (file:///C:/Users/glare/Documents/nuxt3-app/.nuxt/dist/server/server.mjs:83:23)
  at __instantiateModule__ (file:///C:/Users/glare/Documents/nuxt3-app/.nuxt/dist/server/server.mjs:5979:9)
  at __ssrLoadModule__ (file:///C:/Users/glare/Documents/nuxt3-app/.nuxt/dist/server/server.mjs:5926:25)
  at ssrImport (file:///C:/Users/glare/Documents/nuxt3-app/.nuxt/dist/server/server.mjs:5951:13)
  at $id_9abae20e (file:///C:/Users/glare/Documents/nuxt3-app/.nuxt/dist/server/server.mjs:15:37)
  at __instantiateModule__ (file:///C:/Users/glare/Documents/nuxt3-app/.nuxt/dist/server/server.mjs:5979:9)
  at __ssrLoadModule__ (file:///C:/Users/glare/Documents/nuxt3-app/.nuxt/dist/server/server.mjs:5926:25)
  at file:///C:/Users/glare/Documents/nuxt3-app/.nuxt/dist/server/server.mjs:5992:22
  at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
  at async Promise.all (index 0)
```

Environment:

- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27272804.ca557e7`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.2`


Please let me know if you'd like me to open a new issue with this.

**Comment by productdevbook** [comment] 2021-11-08 17:43
@darbyjack this is the same as this repo did you write any extra code?

**Comment by eMeRiKa13** [comment] 2021-11-08 17:44
Same for me, still this error.

The repo preview on Stackblitz doesn't work as well https://stackblitz.com/github/productdevbook/nuxt3-app

**Comment by darbyjack** [comment] 2021-11-08 17:44
> 
> 
> @darbyjack this is the same as this repo did you write any extra code?

No sir. I did a pure clean clone of the repo and did `yarn install` and then `yarn dev` and then this proceeded to lead me to this error.

**Comment by eMeRiKa13** [comment] 2021-11-08 17:46
I think that this pull request will fix the error when it will be merged and released https://github.com/nuxt/framework/pull/1779

**Comment by productdevbook** [comment] 2021-11-08 17:49
Well this problem is not happening to me. Interesting. @eMeRiKa13 maybe thats true. 

I think the problem is a windows path.

**Comment by darbyjack** [comment] 2021-11-08 17:50
Yeah, that would make sense that it's windows. I can test this in a Linux environment shortly.

**Comment by eMeRiKa13** [comment] 2021-11-08 17:54
from the link I posted "Fixing the slash of paths when importing plugins for windows."

I didn't read that before. I'm on Windows, so it seems that

**Comment by florian-lefebvre** [comment] 2021-11-08 18:56
I'm facing the same issue

**Comment by darbyjack** [comment] 2021-11-09 15:59
The mentioned PR has been merged.

**Comment by florian-lefebvre** [comment] 2021-11-10 14:49
I had to add `@nuxt/kit-edge` as a dev dependency to get it work

**Comment by productdevbook** [comment] 2021-11-11 14:30
please test repo, upgraded

**Closed** 2021-11-12 16:32 UTC
Labels: bug
